### ISSUE TITLE
If the k8s deployment mode is used, node indicators cannot be obtained

### ISSUE THREAD

**Issue by kubecto** [utilitywarehouse/kube-summary-exporter#75]
Using k8s mode deployment, the node's metrics cannot be obtained, I tried to use binary available to get
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-summary-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-summary-exporter
spec:
  selector:
    matchLabels:
      app: kube-summary-exporter
  template:
    metadata:
      labels:
        app: kube-summary-exporter
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      hostNetwork: true
      hostPID: true
      serviceAccountName: kube-summary-exporter
      containers:
      - name: kube-summary-exporter
        image: quay.io/utilitywarehouse/kube-summary-exporter:v0.4.3
        ports:
        - name: tcp
          containerPort: 9779
        volumeMounts:
        - mountPath: /host/root
          name: root
          readOnly: false
      volumes:
      - hostPath:
          path: /
        name: root
```

```
curl 10.102.20.67:9779/node/master1
Error querying /stats/summary for master1: unknown (get nodes master1)
```
